# Generated by Django 4.1.5 on 2023-10-23 13:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                validators=[django.core.validators.DecimalValidator],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="de_activate_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.EmailValidator],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid full_name",
                        message="only characters are allowed ",
                        regex="(^[A-Za-z]{3,16})([ ]{0,1})([A-Za-z]{3,25})?([ ]{0,1})?([A-Za-z]{3,25})?([ ]{0,1})?([A-Za-z]{3,25})",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card_number",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid id_card_number",
                        message="only number are allowed",
                        regex="^[0-9]{10}?",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone_number",
                        message="only number are allowed",
                        regex="^[0-9]{11}$",
                    )
                ],
            ),
        ),
    ]
