# Generated by Django 4.1.5 on 2023-10-23 14:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_credit_alter_user_de_activate_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
