# Generated by Django 4.1.5 on 2023-10-26 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid full_name",
                        message="only characters are allowed ",
                        regex="(^[A-Za-z]{3,16})([ ]{0,1})([A-Za-z]{3,45})?([ ]{0,1})?([A-Za-z]{3,25})?([ ]{0,1})?([A-Za-z]{3,15})",
                    )
                ],
            ),
        ),
    ]
