# Generated by Django 4.1.5 on 2023-10-23 13:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="00000000000",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid phone_number",
                                message="only number are allowed",
                                regex="^[0-9]{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[django.core.validators.DecimalValidator],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_raise", models.BooleanField(blank=True, default=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[django.core.validators.DecimalValidator],
                    ),
                ),
                (
                    "to_number",
                    models.CharField(
                        blank=True,
                        default="00000000000",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid phone_number",
                                message="only numbers are allowed",
                                regex="^[0-9]{11}$",
                            )
                        ],
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "to_whom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ctransaction",
                        to="transactions.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="utransactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranactionRaise",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.transaction",),
        ),
    ]
