# Generated by Django 4.1.5 on 2023-10-23 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TranactionRaise",
        ),
        migrations.CreateModel(
            name="TransactionRaise",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.transaction",),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone_number",
                        message="only numbers are allowed",
                        regex="^[0-9]{11}$",
                    )
                ],
            ),
        ),
    ]
