# Generated by Django 4.1.5 on 2023-11-05 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_delete_tranactionraise_transactionraise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                default="00000000000",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone_number",
                        message="only number are allowed",
                        regex="^[0-9]{11}$",
                    )
                ],
            ),
        ),
    ]
